site_name: プロジェクトドキュメント
site_description: システム仕様の統合ドキュメント
site_author: TMMN

# file:// プロトコルで正しく動作させるための設定
use_directory_urls: false

theme:
  name: material
  language: ja
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand  # サイドバー自動展開
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotate

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js

nav:
  - ホーム: index.md
  - ゲーム仕様書:
    - リアクションタイムゲーム: games/reaction-time.md
    - 色当てゲーム: games/color-guess.md
    - 数独（ナンバープレイス）: games/sudoku.md
    - マインスイーパー: games/minesweeper.md
    - リバーシ（オセロ）: games/reversi.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables  # テーブルサポート
  - toc:
      permalink: true
